# Generated by Django 5.2 on 2025-05-05 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('date_published', models.DateTimeField(default=datetime.datetime(2025, 5, 5, 13, 5, 34, 84634, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации')),
                ('image', models.ImageField(upload_to='blog')),
            ],
        ),
    ]
