# Generated by Django 5.2 on 2025-05-10 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_blogpost_author_alter_blogpost_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 18, 19, 57, 410778, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
