# Generated by Django 5.2 on 2025-05-18 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_blogpost_options_alter_blogpost_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 23, 3, 53, 139759, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 23, 3, 53, 139759, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
    ]
